spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: validate

    datasource:
        url: jdbc:mysql://localhost:3306/fullhousedb
        username: demo_user
        password: demo_pass
        driver-class-name: com.mysql.jdbc.Driver